Ahorcado.MVC/Models/Hangman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Ahorcado.MVC.Models
{
    public class Hangman
    {
        [DisplayName("Letra")]
        public String LetterTyped { get; set; }
        [DisplayName("Palabra")]
        public String WordToGuess { get; set; }
        [DisplayName("Letras acertadas")]
        public String GuessingWord { get; set; }
        [DisplayName("Chances Restantes")]
        public Int32? ChancesLeft { get; set; }
        [DisplayName("Letras Erradas")]
        public String WrongLetters { get; set; }

        public Boolean Win { get; set; }

    }
}

Ahorcado.MVC/Controllers/HangmanController.cs
using Ahorcado.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BibliotecaClases;

namespace Ahorcado.MVC.Controllers
{
    public class HangmanController : Controller
    {
        public static Juego Juego { get; set; }

        // GET: Hangman
        public ActionResult Index()
        {
            return View(new Hangman());
        }

        [HttpPost]
        public JsonResult InsertWordToGuess(Hangman model)
        {
            Juego = new Juego(model.WordToGuess);
            model.ChancesLeft = Juego.intentosRestantes;
            return Json(model);
        }

        [HttpPost]
        public JsonResult TryLetter(Hangman model)
        {
            Juego.validarLetra(Convert.ToChar(model.LetterTyped));
            model.Win = Juego.checkearEstadoActual();
            model.ChancesLeft = Juego.intentosRestantes;
            model.WrongLetters = string.Empty;
            foreach (var wLetter in Juego.letrasErradas)
            {
                model.WrongLetters += wLetter + ",";
            }
            model.GuessingWord = string.Empty;
            foreach (var rLetter in Juego.estadoAux)
            {
                model.GuessingWord += rLetter + " ";
            }
            model.LetterTyped = string.Empty;
            return Json(model);
        }
    }
}

Ahorcado.MVC/Views/Hangman/Index.cshtml
@model Ahorcado.MVC.Models.Hangman
@{
    ViewBag.Title = "Index";
}
@{
    string data = new JavaScriptSerializer().Serialize(Model);
}
@section scripts
{
    <script src="~/Scripts/Ahorcado/HangmanVM.js"></script>
    <script type="text/javascript">
        var hangVM = new HangmanVM(@Html.Raw(data));
        ko.applyBindings(hangVM);
    </script>
}

<div class="container">
    <div class="panel panel-default" style="margin-top:20px;">
        <div class="panel-heading">
            <div class="panel-title">Ahorcado</div>
        </div>
        <div class="panel-body form-horizontal">
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="col-sm-3">
                        @Html.LabelFor(m => m.WordToGuess)
                    </div>
                    <div class="col-sm-3">
                        @Html.TextBoxFor(m => m.WordToGuess, new Dictionary<String, object>
                        {
                            { "class", "form-control" },
                            { "data-bind", "value:WordToGuess, enable:enableWordToGuess" },
                            { "type", "password" }
                        })
                    </div>
                    <div class="col-sm-6">
                        <button id="btnInsertWord" class="btn" data-bind="click: insertWordToGuess, enable:enableWordToGuess">Ingresar</button>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-3">
                        @Html.LabelFor(m => m.LetterTyped)
                    </div>
                    <div class="col-sm-3">
                        @Html.TextBoxFor(m => m.LetterTyped, new Dictionary<String, object>
                        {
                            { "class", "form-control" },
                            { "data-bind", "value:LetterTyped, enable: !enableWordToGuess()" },
                            { "maxlength", "1" }
                        })
                    </div>
                    <div class="col-sm-2">
                        <button id="btnInsertLetter" class="btn" data-bind="click: tryLetter, enable: !enableWordToGuess() && ChancesLeft() > 0 && !Win()">Probar</button>
                    </div>
                    <div class="col-sm-2">
                        <button id="btnResetGame" class="btn btn-primary" data-bind="click: resetGame, enable: (Win() || ChancesLeft() == 0) && !enableWordToGuess()">Resetear</button>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.LabelFor(m => m.GuessingWord)
                    </div>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.GuessingWord, new Dictionary<String, object>
                        {
                            { "class", "form-control" },
                            { "data-bind", "value:GuessingWord, enable: false" }
                        })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.LabelFor(m => m.ChancesLeft)
                    </div>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.ChancesLeft, new Dictionary<String, object>
                        {
                            { "class", "form-control" },
                            { "data-bind", "value:ChancesLeft, enable: false" }
                        })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-6">
                        @Html.LabelFor(m => m.WrongLetters)
                    </div>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.WrongLetters, new Dictionary<String, object>
                        {
                            { "class", "form-control" },
                            { "data-bind", "value:WrongLetters, enable: false" }
                        })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<canvas id="hangmanCanvas" width="679" height="290"></canvas>

Ahorcado.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AJ</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/JQueryKnockOut")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ahorcado Main Page", "Index", "Hangman", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

        </footer>
    </div>

    @RenderSection("scripts")
</body>
</html>